version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user123
            POSTGRES_DB: kangwon_document
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        restart: always
    
    db:
        image: postgres:13.3
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user123
            POSTGRES_DB: kangwon_document
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "3030:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: password
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        restart: always

volumes:
    postgres-data:
    pgadmin-data: